version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./web:/var/www/html
    tty: true
    networks:
      - myApp01
  psql:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - ./db/toContainer:/from_host
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    tty: true
    networks:
      - myApp01
networks:
  myApp01:
    external: true